spring.datasource.url=${H2_DB_URL:jdbc:h2:mem:dreamscope;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1}
spring.datasource.username=${H2_DB_USERNAME:sa}
spring.datasource.password=${H2_DB_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
